title: Hunger Fulfills
baseURL: /
params:
  footer:
    content: '&copy; Ujwala Dindi. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: /images/healthy-meals-logo-idea-design.jpg
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest updates and offers.
    subscribe_title: Subscribe
    tagline: ''
  header:
    has_nav: true
    logo_img: ''
    title: Hunger Fulfills
    menu:
      actions: []
  palette: purple
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
